# Comparison of quantum physical ontologies {#sec-Comparison-of-quantum-physical-ontologies}

In discussing ontology in physics both the real and ideal spheres, as introduced by Nicolai Hartmann, play a role. The pure mathematics, applied to construct theory, is in the ideal sphere and the physical entities are in the real sphere. For example, self-adjoint operators exist in quantum theory and they represent observables (properties of things) that exist (this is claimed as a truth) in the physical world. However, it must always be kept in mind that truth claims are fallible.

The ontologies discussed in this chapter are proposals for what exists and does not exist in real sphere interpretations of several formulations of quantum mechanics. These proposals are to be contrasted with the aspect of critical ontology that provides the structures for the investigation. A guiding statement, in the spirit of critical ontology, for this investigation, is that by @maudlin2019:

> A physical theory should clearly and forthrightly address two fundamental questions: what there is, and what it does. This section explores a range of options on 'what there is' in theories that seek to produce identical or very similar empirical results. If the empirical results were not in agreement, then those theories that did not agree with experiment would be eliminated as not being true, although they could still be of theoretical interest. It is because theories with radically different existence claims can have the same empirical consequences that ontology investigation is interesting and relevant.

In what follows familiarity with standard quantum physics, as taught to physics undergraduates, is assumed. If a reminder is needed then Jennan Ismael’s contribution to The Stanford Encyclopedia of Philosophy [@ismael2021] may be helpful.

In the multi-layer model of the real, the discussion that follows deals with physical entities in the inorganic layer. The theories are creations than reside in the objective part of the spiritual layer. There are theories that involve the psychic layer but they will not be considered in this chapter. The psychic layer can only come into play if there is someone there to have perceptions and thoughts.



## Local beables

John Bell [@bell2004jumps], uses his concept of local beables [@bell2004beables] to propose that theses random events are what give effect to local beables. Bell's local beables are a significant development as it was a move away from focusing on what is observed to what exists. The locality of the beable, however, is still tied to the observation that particles such as electrons or photons appear locally in experimental situations. *Beable* also implies a process of coming into being. So, a particle may exist in an interaction or detection but what of the existence of the particle as such? The concept of local beables in general leaves such questions unanswered. The application to GRW will now be considered.

## Wavefunction ontology

In standard quantum physics the wavefunction permits a range of possible events. Of the possible events one happens due to a measurement process. But what happens - what is the physics - when there is no measurement? Ghirardi, Rimini and Weber [@grw1986], (GRW) introduced a supplementary physical effect to standard quantum mechanics that randomly causes the collapse of the wavefunction, creating a way of obtaining macroscopic events from microscopic quantum systems, as will be explained below.

The GRW mechanism is as follows. Let the initial the wave function be

$$\psi (t, q_1, q_2, \dots, q_N)$$

$t$ is time and $q_1, q_2, \dots, q_N$ are position coordinates. The probability per unit time for a GRW spontaneous collapse event is $N/\tau$, where $\tau$ is a new constant of nature, chosen to be in the order of $10^{14}$ seconds. The collapsed wavefunction is

$$\psi' = \frac{j(x - q_n ) \psi(t, \dots)}{R_n (x)},$$

where $q_n$ is chosen at random (probability $=1/N$)

The definition of the weighting function $j$ introduces at least one further constant of nature. This is tuned to be in the region of $10^{-5}$cm to preserve the observed microscopic effects while generating the commonly observed macroscopic world. There is nothing but the wavefunction and the collapse is part of its dynamics.

However, the GRW collapse events happen to the wavefunction, not something else. The wavefunction is then well localized in ordinary space at, at most, a mesoscopic scale. Each is centred on a particular space-time point $(x, t)$. So, Bell proposes these events as providing the local beables of the theory. This would make the beables appearances of the object (Sosein) not a representation of the object itself (Dasein). That being so, these local beables are sparse events in a system of particles and would be very rare for a small number of particles. That is, in the time scales typical of experiment nothing would happen outside the detector. Entanglement provides the mechanism for the commonly experienced existence of macroscopic bodies such as detectors. Note that the spontaneous event is a reduction of the wavefunction. This leaves open the relationship to the charge, mass and spin carrying particle. In addition, if this spontaneously reduced wavefunction is what exists then its relation to the actual particle still needs explanation. Implicitly there is a return to Born probability mechanism but without clarity on this the ontology is incomplete.

### Distributed charge and mass

An alternative wavefunction ontology, but still within GRW theory, proposes that the particle has only a "fuzzy" position, with "more of it" located in places that correspond to its location in configurations which are assigned high amplitudes by the wave-function. This suggests a picture in which the particle is “smeared out” in space, and the effect of the GRW hit is to concentrate most of the smear within $10^{-5}$cm of a particular location. In this ontology the charge and mass of an electron would presumably be distributed across the support of the wavefunction. This theory does propose that a particle exists as such and is extended in space. This therefore provides a more complete ontology.

### The multiverse

A third set of theories are a development of Everett's relative state formulation of quantum mechanics [@everett1957], that are commonly known as many worlds or multiverse interpretations. In this case just the evolving wavefunction features as the candidate entity. The wave function describes all the possibilities for the system and all possibilities happen. This gives rise to many (an infinity of) physical worlds. @wallace2012 provides a comprehensive discussion of this set of theories.

Everett’s criterion for the real existence of a branch is: If the wavefunction $\psi$ of a system is a superposition $a\phi+ b\theta$ then the “branches” $\phi$ and $\theta$ exist, and in each branch, everything physically exists that would exist if that were the entire state of the system. However, there are many ways to represent a function as a linear representation of other functions. Some further structure is required to provide a path to candidates for entities. One approach is an appeal to decoherence, achieved through entanglement. Here the quantity capturing possible states of affairs is $|\psi|^2$ and entanglement can pick out specific decomposition that depends on the physics of the interaction
bohmhiley2006
$$ |\psi |^2 \rightarrow |a\phi|^2+|b\theta|^2$$

That is, there is no interference term. However, the more detailed theory [@wallace2012] works with approximate decoherence.

Examining critically the ontology of many worlds, it shares some of the issues with the GRW theory, especially in the Bell beables version. The smeared, or extended particle interpretation is not available to it but a complete theory must show how familiar phenomena emerge. 

A macro-object is a pattern, and the existence of a pattern as a real thing depends on the usefulness--in particular the explanatory power and predictive reliability--of theories which admit that pattern in their ontology.

What makes a collection of electrons, protons, and neutrons a particle accelerator, rather than something else, has to do with how the microscopic parts are arranged, or structured. A significant part of that structure is the spatial arrangement of the microscopic parts through time. However, a quantum wavefunction contains no microscopic parts localized in space-time, so its behaviour cannot create a macroscopic particle accelerator in anything like the way the behaviour of localized electrons, neutrons, and protons can. The problem remains of how to populate familiar space-time with locally existing entities.

## Bohmian ontology 

Bohmian mechanics [@bohmhiley2006], [@durrteufel2009], is a formulation of quantum mechanics that is constructed to give the same results as that of standard quantum mechanics but in which particles have continuous trajectories. For a discussion of the theory's ontology the mathematics of how this is accomplished is not relevant. The ontology includes:

- Particles with a well-defined position x(t) which varies continuously and is causally determined.
- A guiding field that is derived from the solution of Schrödinger's equation, so that it too changes continuously and is causally determined.
  - The particle is never separate from this guiding field that fundamentally affects it. There is no dynamics without this field.
  - The guiding field is not affected by the particle.

The Bohmian mechanics emphasises that the particle has a continuous trajectory and that these trajectories exist in the physical domain. The particle does not follow the laws of classical dynamics but is guided by a field that is directly derived from the solution to the Schrödinger equation. The claims made about what exists are not made within a wider ontology, but simply posit particles and guiding fIelds. It is tacitly assumed that to exist is to physically exist.

The distinction has been made between existing in the theory (the ideal sphere) and existing physically (the real sphere). There is a version Bohmian mechanics in which the guiding field is not in the real sphere of the ontology but in the ideal sphere. The guiding field is then a law governing the behaviour of the particle but not a physical entity like the particle.  @allori2013 presents this as a primitive ontology. Allori claims that a physical theory

> ... will be about a given primitive ontology: entities living in three-dimensional space or in space-time. They are the fundamental building blocks of everything else, and their histories through time provide a picture of the world according to the theory (the scientific image).

These primitive variables describe what exists in the inorganic layer of the real sphere whereas non-primitive variables exist in the physical theories in the ideal sphere. In a physical situation where no person is active there is no mechanism for the ideal sphere to influence the real sphere. The primitive ontology must therefore include the guiding field so that Bohmian mechanics can operate as a fully-fledged physical theory. However, the wavefunction that gives rise to the guiding field is a function on configuration space, rather than the three-dimensional space of natural phenomena.

## Conclusion

Critical ontology, as an investigative method, has now been applied to a range of proposals that claim the physical existence of particle or wavefunctions or both. Of these it is Bohmian mechanics, with particles and guiding fields as physical entities, that provides the most near to complete physical ontology.

A major deficiency in GRW theories is that the ontological status of the spontaneous reduction of the wavefunction. The mathematical description is of a stochastic process but it is not clear what this process is a property of. This will need a discussion of dispositional properties.

