# Eucken's liberal order {#sec-the-liberal-order}

\index{Eucken, Walter}
\index{liberal order}


Times of crises trigger authoritarian solutions. On the very short time scale this may be but liberal democracies should be resilient enough to return freedoms and within a framework of law and regulation. It’s when freedoms are put on hold that the robust legal framework ensuring the rule of law enables a return to decent liberal democracy. A liberal order is one to which personal freedom is fundamental but recognised the constraints and opportunities afforded by the interaction with others. These interactions will give rise to conflicts and tradeoffs. The freedom to enter into an exchange must be balanced with the freedom not to enter an exchange. Should a shop keeper have the unreserved right not to sell to an individual or should an individual have the right to purchase from an individual goods or services on offer without prejudice? To deal with type of situation rules of interaction are required. Rules will range from international treaties and conventions, national to local laws, regulations and customs. To put this in place there needs to be an interplay of politics, economics and values. The commercial world cannot merely request that the political get out of its way nor that values can be ignored in the pursuit of profit. Where does this leave personal freedom? It cannot be allowed to degenerate into a mere freedom to obey the rules.

It is a great misfortune that “Principles of Political Economy” by Walter Eucken (@eucken2004grundzuge) was never translated into English. His model of a responsible and open liberal market order that addresses the deficiencies of <em>laissez-fair</em> or market fundamentalism as its modern version is sometimes known could form the foundation for addressing the current ills in western economies. This is not just a matter of economic theory. This model provided the blueprint for the new West German economy and social compact after the Second World War. It also needed politicians with the will to implement it, in this case Ludwig Erhard. The astute branding of the model by Alfred Muller-Armack as the Social Market Economy, who became head of policy for Erhard helped form a cross-party consensus in favour of the model but with liberals and conservatives emphasising more the free market aspect and social democrats the social. While politically astute in the short to medium term the initial integrity of the model became diluted as more regulation and control was added during the 1960s.

This chapter will present Euckens model and variants in an attempt to interpret it in the context of current challenges, of which the most significant are growth, fairness, climate change and preclusive action. Climate change and its consequences is an example of an externality that Eucken did not anticipate<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a> but solutions can be found and should be built into the measures that his framework provides.

## Introduction

Liberal economics is taken to start with the work of Adam Smith \index{Smith, Adam}. As this was developed it became known as classical economics. But this term can only apply to a family of attitudes that recognise the strength of markets in allocating scare resources and generating fair prices. Its first phase was largely descriptive and could be thought of as a branch of social philosophy. As its findings started to be recognised for their applicability there was a move to start to treat the subject matter of economics as physicist treat mater, leading to an ever increasing use of mathematical techniques and models. This process has culminated in the mathematical models of neo-classical economics becoming an academic discipline that becomes more and more concerned with its internal system of rewards for research that hold only a tenuous link to practical problems. It is not our purpose here to provide a detailed history of economics but mention the academically dominant neo-classical school to emphasise that the thinkers covered here are distinct and separate from that orthodoxy. The goal here is to describe economic thinking developed st time to deep crisis at any given time, in relation to the thought and contributions of a key economic thinker, is indeed liberal and how far it fall short.
\index{social market}

Neoclassical economics is the economic theory that appears to be most widely in use by experts and is remarkably like physics, in that it is based on a few simple principles, which lead to a rigorous mathematical formulation. This mathematical formulation leads to some basic theorems, which are taken to be an approximate description of a well functioning economy. A large body of results and models has been built up around this theory, and there is a community of experts that express confidence in its basic correctness. However this approach cannot take account of human aspects such as presferences, inventiveness and philanthropy, although narrow self interest is built in.

At the very least, the neoclassical theory of general equilibrium establishes that economics is one of the mathematical sciences. It sets a standard for clarity, rigour and generality that alternative approaches to economics must aim to live up to. This theory is a model that mathematical scientists in other disciplines should be interested to study and understand, because there is a serious claim it has succeeded in capturing something true in a simple mathematical structure about human beings. But if the evolution of the other mathematical sciences is any guide, one cannot expect that a successful theory in a domain is the last word. It is because of its success that we should expect that eventually any mathematical theory of real phenomena is to be replaced by a deeper theory that explains more and corrects misunderstandings.

There are reasons to think that the present is a good time to seek to improve economic theory. There are prominent voices criticizing the neoclassical model, or its offshoots in theories of pricing and risk in financial markets, as having badly failed as a basis of policy advice in the last decade leading to the 2008 economic crisis. Nonetheless it appears to be the case that there is a view among some economists that the model of an economy expressed by the theory of general equilibrium does teach lessons that have implications for policy questions. Among such views is the claim that markets do not require more than minimal regulation because they naturally evolve to a state of stable equilibrium, in which every participant is more satisfied and better off than they would be were the market constrained by external regulation<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a>.

There are also long standing critiques of the neoclassical notion of general equilibrium, some coming from academic economists, others coming from scientists in other disciplines. In real markets there must be dynamics, and an understanding of how equilibrium arises – if it indeed does – from a more general non-equilibrium dynamics is a necessary step to answering many key questions about market behaviour.

Related to this are other fundamental issues about prices. Is a price an absolute quantity, or is it a ratio? In physics we have a basic rule which is that observables are always expressible as ratios of two quantities expressed in the same units, so they are a pure number. Applied to economics, this rule suggests that decisions should not be based on the units or currencies prices are expressed in. Is there a way this can be enforced in the formal treatment? A better observable might be constructed from measuring the result of performing a cycle of trades which begin and end in the same currency. Here one can take the ratio of two prices in the same currency. However, there is a problem, which is that all such quantities are supposed to vanish in equilibrium. But perhaps this is what we want for the non-equilibrium theory. Perhaps these are quantities whose dynamics is responsible for the evolution from non-equilibrium to equilibrium.

### The liberal family

Liberalism does not have its Karl Marx. It evolved through times of trouble due to wars of religion while looking back to classical Greece and Rome for some clues as to how a more stable and tolerable order could be created. This meant abstracting Athenian democracy from the reality of slavery and patriarchy. Add to this the institutionalised privilege in the Roman republic. Many groups and societies have had their councils and while it is difficult to make a case from any one being an ancestor of an existing national assembly many of them a prototype; initial attempts at parliaments. Common to the liberal family is some form of representative parliament. This is fundamental to the political aspect of liberal order. In different places different detailed models have been developed.

Since prehistoric times there have been local market and then there evolved trading rounds between them. These developed in a context of a political order, often closely aligned with an enforced religion, but was tolerated along side these authoritarian structures because of their use in distributing goods and generating revenue. That they also had a side effect of stimulating innovation (technical, ethical and social). Authoritarian regimes can tolerate and even be supportive of technical innovation but ethical and social change needed policing followed by suppression.

## Liberal Principles

### Dimensions of liberalism

One way to try identify something systematic about the wide array of views espoused by liberals depending on their understanding of their principles is to look at how views range along a number of dimensions. Liberals generally support limited government, individual rights (including civil rights and human rights), a markets economy, democracy, secularism, gender equality, racial equality, internationalism, freedom of speech, freedom of the press and freedom of religion. To help evaluation to what extend a particular political and economic order is liberal we will introduce four dimensions.

- Individual: personal liberty is the fundamental concept although constrained by the freedoms of others.
- Political : this derives form the primacy but need to compromise of individual liberty to develop a workable accommodation that sacrifices as little individual freedom as possible.
- Social: the enlightened liberal will be socially tolerant and concerned to address suffering and hardship while insisting on the need to personal responsibility. In this dimension common values that sit constructively with the other dimensions will be values while those who do not share them will be tolerated if at all possible.
- Economic : at a fundamental level this is the freedom to enter or not into an exchange of goods or services.

These values can be treated a dimensions as a range of positions can be taken in them.


### Market fundamentalism

This is a return to laissez-faire. But perhaps it goes further. The expression was popularized by business magnate and philanthropist George Soros in his book The Crisis of Global Capitalism (1998)

### Reformed liberal economics

In this chapter we will look at combining to notions of reform. The first is to change something for the better and the second is to regroup as sports team or a military company would regroup following a set-back.

### What should we expect from theories of markets?

Economics provides an approximate and idealised description of a certain aspects of the world. An economic theory is intended to capture a few aspects of very complex and dynamical emergent phenomena, which occur in large markets in human societies. As such, there is no perfect model, the goal is to enunciate principles, which are general enough, but also powerful enough, to underlie the construction of a variety of models adopted to specific circumstances and questions, and to be the basis of explanation and, to a limited degree, prediction. Because no theory or model can perfectly capture the complexity of an actual economy, all principles, theories and models, must be considered provisional and phenomenological, and continually tested against data<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a>.

To the extent that there is a connection to other areas of science it comes about because the economy is a subset of human activity, which forms a subset of processes in the biosphere. The biosphere is a far from equilibrium system, driven to an approximate, slowly evolving, steady state by the flow of energy through it. It is characterized by cycles of material and energy whose rates of flow are governed by feedback processes acting on diverse scales<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a>. The economy of the world is a subset of that system of cycles and flows which is interesting to us because it is subject to peculiar kinds of decision making, about which we keep records.

Furthermore, an economy is subject to external events and conditions, which being human events are not subject to simple modelling or reliable predictions. So there is a strong limitation in what we can expect from a formal economic theory. But we still can investigate the possibility that there are some principles that lead to models, which can make some useful and testable predictions-at least for the behaviour of markets between their disruptions by unpredictable events and innovations. To the extent that these are robust and independent of the fine-grained details of how human actors make decisions our models will be reliable. This is exactly where behavioural and experimental economics pose challenges to the neoclassical model.

Thus, we are not inclined to side with who suggest that because human behaviour is involved there are no useful regularities that can be captured by mathematical models of a market. Even as we realise that there can be no perfect model of an economy, we seek to replace the Arrow-Debreu model with an alternative that is an example of a useful model, that applies to real people in interaction, and we take its shortcomings as starting points to attempt to improve it rather than as indications that there cannot be a useful general theory of economies and markets.

## The liberal market order

The Keynesian revolution was a response to the realisation that *laissez-faire* was not sufficient to deal with complex national and international trading. In addition the social pressures due to economic dynamics and adjustment could not just be left to play themselves out. An alternative response to this situation was developed in Germany during the 1930s. Evidently a liberal reform program had to be clandestine and camouflaged in abstract academic terms. The intellectual leadership of this activity took place at the University Freiburg, which is still a centre for robust liberalism. The key players were Walter Eucken, Franz Böhm and Hans Großmann-Doerth. The main character in the argument here is Eucken who presented the detailed description of the political and economic order that would permit the operation of a free and open society in “Grundsätze der Wirtschaftspolitik” (“The Principles of Political Economy”) <span class="citation"></span>.

Eucken’s basic idea is the following: “The competitive order is able to properly coordinate investments over the long term. Because with its price mechanism it has the instrument to detect disproportionality and finally to correct them. In this it is superior to all other orders ... Without a competitive order, no state capable of action can emerge and without a competitive state, no competitive order.”<a href="#fn5" class="footnoteRef" id="fnref5"><sup>5</sup></a>

The political order proposed by Eucken, that was labelled the social market economy only later by the politically more pragmatic <a href="https://en.wikipedia.org/wiki/Alfred_Müller-Armack">Alfred Müller-Armack</a>, can be represented as a diagram, Figure [fig:order]. Central to the proposed model is a functioning price system. Prices provide the efficient signals that allows the market to coordinate the allocation of goods and services without a central coordinator. However the whole order needs to be considered as a mutually enforcing system. Indeed the key concept of competition is an aspect of the system as a whole rather than a constituent. An in depth overview has been provided by Karen Horn (@Horn).

### Constituent principles of the market order

The basic principle of the competitive order is a functioning price system. As Eucken was completing his work, the information signalling function of the price system and the impossibility of effective and efficient centralisation was explained by Hayek in *The Use of Knowledge in Society* (@hayek1948individualism). Flexible prices inform sellers about changing shortages and preferences and they also limit the power of all actors through implicit reports of profits and losses and divert scarce resources into efficient uses.

The second principle is the primacy of monetary policy. Around Eucken’s basic principle of a effective price system, the further constituent principles are grouped as inseparable, to be considered necessary and acting simultaneously. The primacy of monetary policy refers to the priority of currency stability. What is required is a stable domestic currency and its external value. The authorities should refrain from deliberately influencing the external value of the domestic currency, for example to promote exports - especially since this leads rapidly to a completely unfruitful devaluation race between countries. A stable domestic and external currency value is required in order not to distort natural relative assessments of current and future domestic and foreign consumption.

The third constituent principle is free market access, both nationally and internationally. That is an essential prerequisite for competition. Walter Eucken formulates his postulate as follows: “... the principle of open markets must apply to the economic policy, , because if they are closed there is the acute danger of obstruction of complete competition.” <a href="#fn6" class="footnoteRef" id="fnref6"><sup>6</sup></a> If markets are not freely accessible and if therefore the“opening up of supply and demand” has not occurred, then the established producers can rest in monopoly-like positions and gradually lose sight of the service to the consumer.

The fourth principle is the right to private property. Philosophically, the right to private property derives from natural law; every human being is considered the owner of himself. The power of disposition over the fruits of their labour is derived from this too. The protection of private property is also considered an essential pillar of the competitive order: only those who have the power to dispose of their possessions can fully devote themselves to competition and exercise their power of disposition in a responsible manner. This principle requires the participation of all citizens; it must also be flanked by effective competition policy.

The fifth principle is freedom of contract or the voluntary nature of all economic decisions. The competitive order is based on the fact that economic decisions are decentralised and made voluntarily. Individual companies and individuals conclude agreements on their transactions and negotiate their terms between themselves - nothing and no one may hinder this. Only when the legal power over the respective property underlying the transactions remains undistorted can the competitive process be such that the economic resources actually flow to the location of their best use. What Eucken wrote on freedom of contract is clear: “First, it is indispensable. Second, freedom of contract can not be granted for the purpose of concluding contracts that restrict or eliminate the freedom of contract.”<a href="#fn7" class="footnoteRef" id="fnref7"><sup>7</sup></a>

The sixth constituent principle is liability. This principle is particularly important, as has become very clear in the wake of the international financial and economic crisis. Its neglect in many areas of the economy and wider society has given us the 2008 crisis in the first place. The principle of liability is so crucial because only those who are fully liable for the consequences of their actions are really responsible. Only liability ensures that all those involved in the competition are behaving in a fair rather than exploitative manner, even though they may not have a corresponding moral compass. Liability thus ensures that competition is not unfair, but can be relied on to ensure performance and delivery.

The last of the seven constituent principles, Consistency of Economic Policy, concerns politics. One should not be tempted to dismiss this as a less important for this reason. On the contrary, on the question of the role of the state an essential minimum condition is defined. The principle of the consistency of economic policy demands that the political conditions will be reliably predictable, so that the economic actors can plan. This requirement applies in general.

### Regulatory principles of the market order

The first principle is competition policy. Concentrations of power must be prevented. Competition policy in the narrower sense deals with targeted interventions against cartels and monopolies. The justification for such interventions is that the competitive order must prevent the formation of permanent positions of power, no matter what their nature. However, since Eucken, economic theory has undergone a development that verifiably shows that it does not depend so much on the actual absence of monopolies. It is more important that the markets are open to competitors and not isolated. A monopolist who can not rest will ultimately provide just as good a supply to consumers as a competitive company.For foreign markets, this idea is even contained in the third constituent principle of Walter Eucken, the principle of open markets; but the application to domestic markets can also be subsumed under it. This competition policy must also act with general principles and avoid discrimination.

The second principle is income redistribution. A certain degree of redistribution as a correction of the distribution of income as it arises spontaneously in the market is quite reasonable and permissible in the rules of competition. Eucken makes it his second regulating principle. The second principle, however, is subordinate to the first principle; it does not stand for itself. It therefore does not include any - possibly socio-politically motivated - correction of the market result, which makes it imperative to redeem the social market economy’s promise of social compensation. On the contrary, the income redistribution always has the task of strengthening the price mechanism and thus the efficiency of the market. That makes them part of the regulatory policy.By contrast, an independently operated, self-reliant distribution policy would reach deep into the realms of process policy. Distributional corrections run the risk of weakening them. They are always a balancing act.

As the third regulating principle Walter Eucken called the improvement of the “economic calculation”. With this he expanded the constituent principle of liability. By “economic accounting” is meant entrepreneurs completed, not necessarily includes all macroeconomic costs. Today, economists speak of “external effects” in this context. External effects are costs or benefits of those who are not involved, which are caused as side effects in connection with a specific microeconomic decision, but are not taken into account. Such side effects are common. Eucken remarked: “The system works very well, but it does not take into account the repercussions which the individual economic plans and their execution exert on the macroeconomic data - if these repercussions are not felt in the own planning area of the individual management. [...] Consider the destruction of forests in America. ”

Walter Eucken’s fourth regulating principle addresses a topic that affects the labour market. This topic has recently rekindled public discussion in Germany in connection with the introduction of minimum wages. It’s about the possibility that falling wages do not lead to a fall off of work but on the contrary to an increase. However, Walter Eucken considers this effect to be a rare special case. Because he assumed that a worker in a flexible competitive order with falling wages simply moves to another job or another region: “In free movement and professional mobility of work, the solution is facilitated through other occupations.” If this possibility, however is de facto limited, for example, by local demand monopolies for workers, then, according to Eucken, the state with minimum wages to counteract to thwart exploitation - but only then.

So that was the system of “constituent and regulating principles” that the Freiburg economist Walter Eucken designed more than sixty years ago. These principles of competitive order are timeless. Even today, they can be used as an objective yardstick for politics, even and especially in times of crisis. The “Freiburg Imperative” contains the core of the neoliberal project. It is the basis of the social market economy.

## Externalities


## Preclusive action

## Conclusions

<div class="footnotes">
<hr />
<ol>
<li id="fn1">Climate change was anticipated early in the 20th century but was not widely recognised as a priority in the first half of the century. In 1896, a Swedish chemist, Svante Arrhenius noticed that the gas carbon dioxide (CO2) was especially good at trapping heat radiation. He realised that this meant that the massive increases in atmospheric CO<span class="math inline"><em></em><sub>2</sub></span>, caused by coal burning during the industrial revolution, would fuel Fourier’s greenhouse effect and lead to global warming of the planet.<a href="#fnref1">↩</a></li>
<li id="fn2">To anticipate one conclusion of the following, it does not appear to be the case that an objective reading of the mathematical theory of neoclassical economics provides an argument for laissez-faire economics over a mixed economy or for limiting regulation of financial markets. The case for free markets is more subtle and depends on valuing individual freedom and showing that free markets facilitate this freedom.<a href="#fnref2">↩</a></li>
<li id="fn3">This is generally the case for scientific theories.<a href="#fnref3">↩</a></li>
<li id="fn4">Neglecting to take account of undesirable effects of economic activity, such as global warming, can be brought into the model and through the price mechanism leading to a number of proposals for carbon pricing <span class="citation"></span>.<a href="#fnref4">↩</a></li>
<li id="fn5">,,Die Wettbewerbsordnung ist imstande, die Investitionen auf die Dauer richtig aufeinander abzustimmen. Denn sie besitzt mit ihrer Preismechanik das Instrument, um Disproportionalitäten festzustellen und um sie schließlich zu korrigieren. Darin ist sie allen anderen Ordnungen überlegen … Ohne eine Wettbewerbsordnung kann kein aktionsfähiger Staat entstehen und ohne einen aktionsfähigen Staat keine Wettbewerbsordnung.”<a href="#fnref5">↩</a></li>
<li id="fn6">,, … muss für die Wirtschaftspolitik der Grundsatz gelten, die Öffnung der Märkte durchzuführen, weil bei ihrer Schließung die akute Gefahr der Behinderung der vollständigen Konkurrenz gegeben ist.”<a href="#fnref6">↩</a></li>
<li id="fn7">,,Erstens: Sie ist unentbehrlich. Zweitens: Vertragsfreiheit darf nicht zu dem Zwecke gewährt werden, um Verträge zu schließen, welche die Vertragsfreiheit beschränken oder beseitigen.”<a href="#fnref7">↩</a></li>
</ol>
</div>
