# Ontological Framework: Nicolai Hartmann and Quantum Mechanics {#sec-heart-of-matter}


The ontological framework for this blog is from Nicolai Hartmann's *new ontology programme* that was developed in a number of very substantial publications in the first half of the 20th century. In my interpretation of it, it is the open and pluralistic nature of Hartmann's new ontology that is most attractive. It can include categories of substance, process, organism, consciousness and more. Its layer structure allows the discussion of emergence of multiple entities and supervenience, whatever the ultimate ontological status of the layer model. The openness and pluralism is more important to me than the layered ontology. However, many chapters are specifically about quantum mechanics. Quantum mechanics was already making confirmed predictions when Hartmann was writing, and he provided some analysis, but, did noy get much further than identifying that quantum mechanics would provide some ontological challenges. In Hartmann's layered ontological model the foundation is the inorganic stratum, with categories such as space, time, process and substance.

At one stage it was thought that the challenges of quantum mechanics could have a solution in epistemology. However, the problem was that the physics is incomplete and so the problem was not just that of interpretation. The ontological status of the theory can not be fully addressed without repairing the physics. The major flaw in standard quantum mechanics, as discussed in other chapters, is that there is no physical explanation of events.

As a theory that includes a physical explanation of events, consider Ruth Kastner's relativistic transactional interpretation (RTI) [@kastner2022transactional] as a working theory that plugs the holes in the physics that were the main concern. For ontological analysis, the most significant aspect of RTI is the nature of the quantum substratum and its relationship with the empirical domain. Ruth Kastner does address metaphysical issues but here an indeprendent view will be presented. The analysis of the physics is for a universe that *is* independent of a knowing subject [@Popper1972].

## Ontological status of quantum substratum

The quantum substratum is a domain of potentiality. It is not only not observable; it is not actual. The only indictor of its nature is the mathematical theory that relates it to actual events. This mathematical theory could be treated as a mere prediction and technology instrument. However I want to examine how the universe could be in itself. The potentiality substratum is real in that it is the source of physical events.

A potentiality interpretation of quantum mechanics is not an innovation of RTI. It was proposed by Heisenberg [@heisenberg1958physics] and is championed by researchers who do not adopt RTI [@kastner2018]. The three authors, it seems, could not agree with Ruth Kastner on adopting RTI as the best current explanation. The other authors are strongly influenced by A N Whitehead's process metaphysics [@whitehead2010]. On a first pass, a metaphysics with a fundamental event and process ontology, such as Whitehead's, seems consistent with RTI. however, there are many details and interpretations of Whitehead's metaphysics that I have yet to engage with.

In RTI events take place due to a transaction process in the substratum. Processes in the quantum substratum are disposed to create events that manifest in space-time and shape the future potential manifestation of events (objective quantum state reduction). The process can be summarised:

1. The physical system, described by relativistic quantum mechanics, evolves to a state that is favourable to a set of possible transactions.
2. The context of these possible transactions (at a given time in the substratum dynamics) and the state of the system defines a complete set of transition probabilities from a complex of incommensurable possible transitions.
3. One of the possible transitions takes place. This is, as far as the mathematical description guides, a physical stochastic process step.
4. The outcome is a space-time event and a change in the substratum state conditioned on that event.

Why should a quantum substratum of pure potentiality give rise to space-time events? In the mathematical structure describing the physics of the substratum time is a category and, space and momentum are among the potentialities. It would be conceivable that events would appear in a space-time block universe. Alternatively it is the relationship among the events that constitute space-time [@kastner2022transactional]. Space-time is emergent and not ontological fundamental if the events are the elements of its fabric. Fundamentally there are no substances. For example, quantum states describing electrons represent entities that cannot exhibit all their potential attributes at the same times. The picture in which quantum mechanics is a modification of classical mechanics that can keep the substance-particle as the fundamental ontology is no longer defendable. Classically Matter is fundamental, now, in the quantum description adopted here, matter-like entities emerge in a dynamic network of event relationships. This is a profound ontological innovation even greater than the introduction of electromagnetic fields.

Whatever the final status of a layered ontology turns out to be, I think that it will be useful in examining how, in detail, a substratum of pure potentiality can give rise to a rich world of physics, biology, psychology, society and culture.
